# Generated by Django 5.2 on 2025-05-15 21:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Boards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('board_id', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x_coordinate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('y_coordinate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('type', models.CharField(choices=[('img', 'images'), ('txt', 'texts'), ('stick', 'sticky_notes')], max_length=15)),
                ('content', models.JSONField()),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiroBoards.boards')),
            ],
        ),
        migrations.CreateModel(
            name='UserBoardRelations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_token', models.CharField(max_length=512)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiroBoards.boards')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='boards',
            name='users',
            field=models.ManyToManyField(through='MiroBoards.UserBoardRelations', to=settings.AUTH_USER_MODEL),
        ),
    ]
