# Generated by Django 5.2 on 2025-05-15 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiroBoards', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='boards',
            name='name',
            field=models.CharField(default='board', max_length=100),
            preserve_default=False,
        ),
    ]
