# Generated by Django 5.2 on 2025-05-15 21:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiroBoards', '0002_boards_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boards',
            name='users',
        ),
        migrations.AddField(
            model_name='boards',
            name='api_key',
            field=models.CharField(default='1', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boards',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='UserBoardRelations',
        ),
    ]
