# Generated by Django 5.2 on 2025-05-16 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiroBoards', '0003_remove_boards_users_boards_api_key_boards_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='item_id',
            field=models.CharField(default=0),
        ),
    ]
