# Generated by Django 5.2 on 2025-05-22 21:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiroBoards', '0004_items_item_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='MiroBoards.boards'),
        ),
        migrations.AlterField(
            model_name='items',
            name='item_id',
            field=models.CharField(db_index=True, default=0),
        ),
    ]
